spring:
  profiles:
    active:
      - dev
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./rainbow-prod
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
rainbow:
  upload-path: uploads-prod
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:rainbow-dev
rainbow:
  upload-path: uploads-dev
---
spring:
  profiles: test
rainbow:
  upload-path: uploads-test